name: Runner Setup POC
description: Set up the environment of a GitHub-hosted runner using this composite action.
inputs:
  node-version:
    description: 'Node Version'
    required: true
    default: '18'
runs:
  using: 'composite'
  steps:
    - name: adding github workspace as safe directory
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash
    - uses: actions/checkout@v4

    - name: Install Python3-Pip
      run: sudo apt-get update
      shell: bash

    - name: Install Node.js
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    
    - if: ${{ steps.node-setup.outputs.cache-hit == 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list
      shell: bash

    - name: Install Salesforce CLI, Vlocity, and Plugins
      if: ${{ steps.node-setup.outputs.cache-hit != 'true' }}
      run: npm install
      shell: bash

    # - name: Install Salesforce CLI Plugins
    #   run: echo "y" | sf plugins install @salesforce/sfdx-scanner @salesforce/acu-pack@2.0.4
    #   shell: bash

    # - name: Install Python Plugins
    #   run: python3 -m pip install pyyaml
    #   shell: bash
