name: Runner Setup POC
description: Set up the environment of a GitHub-hosted runner using this composite action.
inputs:
  node-version:
    description: 'Node Version'
    required: true
    default: '18'
runs:
  using: 'composite'
  steps:
    - name: adding github workspace as safe directory
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash
    - uses: actions/checkout@v4
    - name: Install TZ Data
      run: sudo apt-get update -y && DEBIAN_FRONTEND=noninteractive TZ=US sudo apt-get install -y tzdata
      shell: bash

    - name: Install Java and Other Components
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
        software-properties-common \
        jq \
        unzip \
        curl \
        gnupg \
        gpg \
        default-jdk \
        python3-pip
      shell: bash

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Salesforce CLI, Vlocity, and Plugins
      run: |
        npm install --global @salesforce/cli vlocity dotenv-cli &&\
        echo "y" | sf plugins install @salesforce/sfdx-scanner @salesforce/acu-pack@2.0.4
      shell: bash

    - name: Install Python Plugins
      run: python3 -m pip install pyyaml
      shell: bash

    # - name: Give Root Access To Running User
    #   run: |
    #     chmod -R go+rwx ${HOME} &&\
    #     chmod -R go+rwx /root