name: Runner Setup POC
description: Set up the environment of a GitHub-hosted runner using this composite action.
inputs:
  node-version:
    description: 'Node Version'
    required: true
    default: '18'
runs:
  using: 'composite'
  steps:
    - name: adding github workspace as safe directory
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
      shell: bash
    - uses: actions/checkout@v4

    - name: Install Python3-Pip
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
        python3-pip
      shell: bash

    - name: Install Node.js
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Get NPM Cache Dir
      id: npm-cache-dir
      run: cho "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    
    - name: NPM Cache
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Salesforce CLI, Vlocity, and Plugins
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: |
        npm install @salesforce/cli vlocity dotenv-cli &&\
        echo "y" | sf plugins install @salesforce/sfdx-scanner @salesforce/acu-pack@2.0.4
      shell: bash

    - name: Install Python Plugins
      run: python3 -m pip install pyyaml
      shell: bash
